### ISSUE TITLE
Additional options when creating volume

### ISSUE THREAD

**Issue by HighWatersDev** [AdrianBronder/ntap-automation#1]
Hi,

Thanks for this excellent collection of scripts. I was going through netapp api docs trying to figure out how I can add more options when creating nfs volume. Things like -autosize-grow-threshold-percent, -policy, -space-guarantee, -autosize-mode etc.

I just wanted to see if you could point me in the right direction.

Thanks!

**Comment by AdrianBronder** [comment]
Happy that you like it! You can access the API reference on the support portal:
https://library.netapp.com/ecmdocs/ECMLP2862544/html/index.html#/
or directly on your ONTAP cluster:
https://\<cluster-mgmt\>/api/docs

In the category "storage" you will find "POST /storage/volumes". Scroll down and you will find a full example and a link "Model" next to it describing all parameters in detail. 

@HighWatersDev Does this help you?
